export function buildDeathScreenProps({
  score,
  kills,
  deaths,
  wave,
  level,
  bestStreak,
  timeSurvived,
  totalDamage,
  stats = {},
  deathMessage,
  difficulty,
  runSeed,
  runModifier,
  runModifiers = [],
  achievementsUnlocked,
  activePerks,
  missionsSummary,
  leaderboard,
  lbLoading,
  lbHasMore,
  onLoadMore,
  username,
  DIFFICULTIES,
  onStartGame,
  onMenu,
  onRefreshLeaderboard,
  onSubmitScore,
  highlightGifUrl,
  gifEncoding,
  fmtTime,
  gamepadConnected,
  controllerType,
  weaponKills,
  starterLoadout,
  traceEvidence,
  gs = null,
  proximityRivals,
  bossKillCount,
  weaponMilestones,
  cosmeticUnlocks,
  objectivesSummary,
  scoreAttackMode,
  dailyChallengeMode,
  bossRushMode,
  cursedRunMode,
  speedrunMode,
  gauntletMode,
  challengeVsScore,
  challengeVsName,
  onInstallApp,
  experimentMatched,
  peakMoment,
  communityChokeWaves,
} = {}) {
  return {
    score,
    kills,
    deaths,
    wave,
    level,
    bestStreak,
    timeSurvived,
    totalDamage,
    crits: stats.crits,
    grenades: stats.grenades,
    deathMessage,
    difficulty,
    runSeed,
    runModifier: runModifiers.find((modifier) => modifier.id === runModifier) || null,
    achievementsUnlocked,
    activePerks,
    missionsSummary,
    leaderboard,
    lbLoading,
    lbHasMore,
    onLoadMore,
    username,
    DIFFICULTIES,
    onStartGame,
    onMenu,
    onRefreshLeaderboard,
    onSubmitScore,
    highlightGifUrl,
    gifEncoding,
    fmtTime,
    gamepadConnected,
    controllerType,
    weaponKills,
    bestPrecisionStreak: stats.bestPrecisionStreak || 0,
    starterLoadout,
    traceEvidence,
    precisionPeakFrame: gs?._precisionPeakFrame || 0,
    precisionPeakStreak: gs?._precisionPeakStreak || 0,
    proximityRivals: proximityRivals || gs?.proximityRivals || [],
    nearDeathEvents: gs?._nearDeathEvents || [],
    flowStateFired: gs?._flowStateFiredCount || 0,
    bossKillCount,
    weaponMilestones,
    cosmeticUnlocks,
    objectivesSummary,
    scoreAttackMode,
    dailyChallengeMode,
    bossRushMode,
    cursedRunMode,
    speedrunMode,
    gauntletMode,
    playerSkin: gs?.playerSkin || "",
    vsScore: challengeVsScore,
    vsName: challengeVsName,
    ghostKey: gs?._ghostKey,
    onInstallApp,
    experimentMatched,
    peakMoment,
    waveScoreLog: gs?._waveScoreLog || [],
    communityChokeWaves,
  };
}

export function buildDeathCoachTelemetry({
  postRunTelemetry = {},
  eventDigest = null,
  runCoach = {},
} = {}) {
  const chokeWarning = runCoach?.brain?.chokeWarning || null;
  return {
    ...postRunTelemetry,
    digestVersion: eventDigest?.v ?? null,
    coaching: {
      weaponTipShown: Boolean(runCoach.weaponTip),
      weaponMismatchShown: Boolean(runCoach.weaponDeathTip),
      precisionTipShown: Boolean(runCoach.precisionTip),
      crossRunPatternShown: Boolean(runCoach.crossRunTip),
      enemyLabShown: Boolean(runCoach.enemyLab),
      chokeWarningShown: Boolean(chokeWarning),
    },
    weaponDeathTip: runCoach.weaponDeathTip || null,
    chokeWarning: chokeWarning
      ? {
          wave: chokeWarning.wave ?? null,
          tip: chokeWarning.tip || "",
        }
      : null,
  };
}
