-- Complete run facts, public aggregate truth, player feedback, and synthetic isolation.

ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS feedback_difficulty text;
ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS total_shots integer NOT NULL DEFAULT 0;
ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS total_hits integer NOT NULL DEFAULT 0;
ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS total_crits integer NOT NULL DEFAULT 0;
ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS boss_kills integer NOT NULL DEFAULT 0;
ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS is_synthetic boolean NOT NULL DEFAULT false;
ALTER TABLE leaderboard ADD COLUMN IF NOT EXISTS source_run_token text;

DO $$ BEGIN
  ALTER TABLE leaderboard ADD CONSTRAINT leaderboard_feedback_difficulty_check
    CHECK (feedback_difficulty IS NULL OR feedback_difficulty IN ('too_easy', 'dialed_in', 'brutal'));
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- The health check is deliberately exact: a player who happens to use an hc-
-- callsign is not hidden unless every stable automation marker also matches.
UPDATE leaderboard
SET is_synthetic = true
WHERE name LIKE 'hc-%'
  AND seed = 424242
  AND "lastWords" = 'health-check clear'
  AND score = 1875
  AND kills = 24
  AND wave = 5;

DROP POLICY IF EXISTS "public_read_leaderboard" ON leaderboard;
CREATE POLICY "public_read_leaderboard"
  ON leaderboard FOR SELECT
  USING (quarantined = false AND is_synthetic = false);

CREATE INDEX IF NOT EXISTS idx_leaderboard_public_player_rank
  ON leaderboard (game_id, score DESC)
  WHERE quarantined = false AND is_synthetic = false;

CREATE TABLE IF NOT EXISTS game_run_facts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_key text NOT NULL UNIQUE,
  player_key uuid NOT NULL,
  user_id uuid,
  game_id text NOT NULL DEFAULT 'cod',
  callsign text NOT NULL DEFAULT 'Anonymous',
  mode text NOT NULL DEFAULT 'standard',
  difficulty text NOT NULL DEFAULT 'normal',
  seed integer,
  score integer NOT NULL DEFAULT 0,
  kills integer NOT NULL DEFAULT 0,
  wave integer NOT NULL DEFAULT 1,
  duration_s integer NOT NULL DEFAULT 0,
  total_damage integer NOT NULL DEFAULT 0,
  total_shots integer NOT NULL DEFAULT 0,
  total_hits integer NOT NULL DEFAULT 0,
  total_crits integer NOT NULL DEFAULT 0,
  boss_kills integer NOT NULL DEFAULT 0,
  feedback_difficulty text,
  last_words text,
  practice boolean NOT NULL DEFAULT false,
  is_synthetic boolean NOT NULL DEFAULT false,
  completed_at timestamptz NOT NULL DEFAULT now(),
  received_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT game_run_facts_mode_check CHECK (mode IN ('standard','normal','score_attack','daily_challenge','boss_rush','cursed','speedrun','gauntlet','zombies')),
  CONSTRAINT game_run_facts_difficulty_check CHECK (difficulty IN ('easy','normal','hard','insane')),
  CONSTRAINT game_run_facts_feedback_check CHECK (feedback_difficulty IS NULL OR feedback_difficulty IN ('too_easy','dialed_in','brutal')),
  CONSTRAINT game_run_facts_nonnegative_check CHECK (
    score >= 0 AND kills >= 0 AND wave >= 1 AND duration_s >= 0 AND
    total_damage >= 0 AND total_shots >= 0 AND total_hits >= 0 AND total_crits >= 0 AND boss_kills >= 0
  )
);

ALTER TABLE game_run_facts ENABLE ROW LEVEL SECURITY;
CREATE INDEX IF NOT EXISTS idx_game_run_facts_public_aggregate
  ON game_run_facts (game_id, completed_at DESC)
  WHERE practice = false AND is_synthetic = false;

CREATE OR REPLACE FUNCTION get_cod_community_stats()
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH trusted_facts AS (
    SELECT
      player_key::text AS runner_key, mode, score, kills, wave, duration_s,
      total_damage, total_shots, total_hits, total_crits, boss_kills,
      feedback_difficulty, completed_at
    FROM game_run_facts
    WHERE game_id = 'cod' AND practice = false AND is_synthetic = false
  ), legacy_rows AS (
    SELECT
      'legacy:' || lower(coalesce(name, 'anonymous')) AS runner_key,
      coalesce(nullif(mode, ''), 'standard') AS mode,
      coalesce(score, 0) AS score,
      coalesce(kills, 0) AS kills,
      greatest(1, coalesce(wave, 1)) AS wave,
      CASE WHEN time ~ '^\\d+:[0-5]\\d$'
        THEN split_part(time, ':', 1)::integer * 60 + split_part(time, ':', 2)::integer ELSE 0 END AS duration_s,
      coalesce("totalDamage", 0) AS total_damage,
      coalesce(total_shots, 0) AS total_shots,
      coalesce(total_hits, 0) AS total_hits,
      coalesce(total_crits, 0) AS total_crits,
      coalesce(boss_kills, 0) AS boss_kills,
      feedback_difficulty,
      coalesce(created_at, to_timestamp(coalesce(ts, 0) / 1000.0), now()) AS completed_at
    FROM leaderboard l
    WHERE coalesce(quarantined, false) = false
      AND coalesce(is_synthetic, false) = false
      AND NOT EXISTS (SELECT 1 FROM game_run_facts f WHERE f.run_key = l.source_run_token)
  ), all_runs AS (
    SELECT * FROM trusted_facts
    UNION ALL
    SELECT * FROM legacy_rows
  ), mode_counts AS (
    SELECT coalesce(jsonb_object_agg(mode, count), '{}'::jsonb) AS value
    FROM (SELECT mode, count(*)::integer AS count FROM all_runs GROUP BY mode) grouped
  )
  SELECT jsonb_build_object(
    'scope', 'verified_completed_runs_plus_legacy_public_scores',
    'runs', count(*),
    'runners', count(DISTINCT runner_key),
    'hours', round(coalesce(sum(duration_s), 0)::numeric / 3600, 1),
    'kills', coalesce(sum(kills), 0),
    'score', coalesce(sum(score), 0),
    'damage', coalesce(sum(total_damage), 0),
    'shots', coalesce(sum(total_shots), 0),
    'hits', coalesce(sum(total_hits), 0),
    'bosses', coalesce(sum(boss_kills), 0),
    'bestScore', coalesce(max(score), 0),
    'bestKills', coalesce(max(kills), 0),
    'bestWave', coalesce(max(wave), 0),
    'runs24h', count(*) FILTER (WHERE completed_at >= now() - interval '24 hours'),
    'kills24h', coalesce(sum(kills) FILTER (WHERE completed_at >= now() - interval '24 hours'), 0),
    'feedback', jsonb_build_object(
      'too_easy', count(*) FILTER (WHERE feedback_difficulty = 'too_easy'),
      'dialed_in', count(*) FILTER (WHERE feedback_difficulty = 'dialed_in'),
      'brutal', count(*) FILTER (WHERE feedback_difficulty = 'brutal')
    ),
    'modes', (SELECT value FROM mode_counts),
    'updatedAt', max(completed_at)
  ) FROM all_runs;
$$;

REVOKE ALL ON FUNCTION get_cod_community_stats() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION get_cod_community_stats() TO anon, authenticated, service_role;

COMMENT ON TABLE game_run_facts IS 'Private per-run authority for complete Call of Doodie statistics; public access is aggregate-only through get_cod_community_stats().';
COMMENT ON FUNCTION get_cod_community_stats() IS 'Public aggregate excluding practice, quarantined, and exact health-check automation rows.';
