-- Browser-local Studio event mirror for Call of Doodie.
-- Lets front-door, debrief, trust, rivalry, and telemetry events sync
-- without changing the local-first UX contract.

CREATE TABLE IF NOT EXISTS studio_game_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_event_id TEXT NOT NULL UNIQUE,
  uid UUID NULL,
  client_uid UUID NULL,
  game_id TEXT NOT NULL DEFAULT 'cod',
  schema_name TEXT NOT NULL DEFAULT 'vaultspark.game-event.v1',
  contract_version INTEGER NOT NULL DEFAULT 1,
  type TEXT NOT NULL,
  category TEXT NOT NULL,
  surface TEXT NOT NULL,
  summary TEXT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  event_created_at TIMESTAMPTZ NOT NULL,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_studio_game_events_game_created
  ON studio_game_events (game_id, event_created_at DESC);

CREATE INDEX IF NOT EXISTS idx_studio_game_events_type_created
  ON studio_game_events (type, event_created_at DESC);

CREATE INDEX IF NOT EXISTS idx_studio_game_events_client_uid
  ON studio_game_events (client_uid, event_created_at DESC);

ALTER TABLE studio_game_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "studio_game_events_select_none" ON studio_game_events;
CREATE POLICY "studio_game_events_select_none"
  ON studio_game_events
  FOR SELECT
  USING (false);
